# These are supported funding model platforms

github: Stryk91
# patreon: # Add if you create one
# ko_fi: # Add if you create one
# buy_me_a_coffee: # Add if you create one
# open_collective: # Add if you create one
# custom: ["https://your-link.com"] # Add custom links if needed
